[workspace.package]
authors = ["qdot3"]
edition = "2021"

keywords = []
publish = false

readme = "/README.md"
license = "MIT"
license-file = "/LICENSE"

exclude = ["/rust-toolchain.toml"]

[workspace]
resolver = "2"
members = [
    "crates/foldable_deque",
    "crates/foldable_queue",
    "crates/op_add",
    "crates/op_affine",
    "crates/op_max",
    "crates/op_min",
    "crates/segtree",
    "crates/segtree_dual",
    "crates/segtree_lazy",
    "crates/traits",
]

[workspace.dependencies]
from_bytes = { git = "https://github.com/qdot3/lib-cp" }
input = { git = "https://github.com/qdot3/lib-cp" }
output = { git = "https://github.com/qdot3/lib-cp" }
reader = { git = "https://github.com/qdot3/lib-cp" }
compress = { git = "https://github.com/qdot3/lib-cp" }

[workspace.lints]
clippy.pedantic = "warn"
# clippy.restriction = "warn"
# clippy.cargo = "warn"

# clippy.implicit_return = { level = "allow", priority = 1 }
# clippy.indexing_slicing = { level = "allow", priority = 1 }
# clippy.arithmetic_side_effects = { level = "allow", priority = 1 }
# clippy.min_ident_chars = { level = "allow", priority = 1 }
