[package]
name = "foldable_deque"
version = "0.3.0"
authors.workspace = true
edition.workspace = true
keywords.workspace = true
publish.workspace = true
readme.workspace = true
license.workspace = true
exclude.workspace = true

[dependencies]
traits = { path = "../traits" }

[lints]
workspace = true

[dev-dependencies]
input.workspace = true
output.workspace = true
from_bytes.workspace = true
